# Generated by Django 4.2.5 on 2023-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
